* task-cabinet-server [spec]
  to define data validation

** Processing
   definition
   - [X] user validation [[./doc/user.md]]
   - [X] user-task validation  [[./doc/task.md]]
   - [X] user-token validation  [[./doc/user_token.md]]
   - [X] user-devicce validation  [[./doc/user_device.md]]

  implementation
   - [X] user validation
   - [X] user-task validation
   - [X] user-token validation
   - [X] user-devicce validation
** Installation
ref. https://github.com/MokkeMeguru/tcs-notification

Copy `profiles.clj` from the above repository.

example:

#+begin_src clojure
{:dev  {:env
        {:database-url "jdbc:postgresql://dev_db:5432/tcs_db?user=<user-name>&password=<password>"
         :env "dev"}}
 :test {:env
        {:database-url "jdbc:postgresql://dev_db:5565/tcs_db?user=<user-name>&password=<password>"
         :env "test"}}}
#+end_src

** Usage

#+begin_src shell
docker-compose build
docker-compose run --service-port repl
lein repl
(reset-migrate)
(start)
#+end_src

accessing http://localhost:3000, You can see swagger view. Call any endpoint according to its description.

** Options

** Bugs


** That You Think


** License

Copyright © 2019 MokkeMeguru

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.

